-- Consulta todos los alumnos de la plataforma ordenados por nombre
-- Consulta todos los procesores de la plataforma ordenados por DNI
-- Consulta todos los ciclos existentes ordenados por familia descendente
-- Consulta todos los ciclos existentes cuya sigla empiece por D
-- Selecciona todos los profesores del departamento de Informática.
-- Muestra el nombre completo de los profesores que no tienen un segundo apellido.
-- Lista los módulos impartidos en el ciclo DAM.
-- Encuentra los profesores que no están asignados a ningún departamento.
-- Muestra los nombres de los profesores junto con el nombre de su departamento.
-- Cuenta el número de profesores por departamento. Debe aparecer el nombre del departamento y total de profesores.
-- De la consulta anterior, solo obten el que más numero de profesores tienen.
-- Encuentra el nombre y apellidos de los profesores que imparten módulos en el primer curso.
-- Lista todos los módulos bilingües.
-- Muestra los módulos que tienen más de 200 horas.
-- Encuentra el nombre y apellidos de los profesores que no tienen asignado un correo electrónico.
-- Muestra el nombre del ciclo y el nombre de la familia correspondiente.
-- Lista los nombres de los módulos y las notas obtenidas por los alumnos.
-- Lista los nombres de los módulos, el nombre del alumno y las notas.
-- Encuentra el nombre del profesor que imparte el módulo con el código 3.
-- Muestra el nombre del profesor director de cada departamento.
-- Lista los nombres de los alumnos que nacieron después del año 2000.
-- Cuenta el numero de módulos impartidos por cada profesor.
-- Muestra el número total de horas de cada ciclo. Debe mostrar el ciclo y las horas totales.
-- Lista los módulos ordenados por nombre.
-- Encuentra el nombre y apellidos de los profesores que imparten módulos en el segundo curso.
-- Muestra el número de módulos impartidos en cada ciclo. Debe aparecer el ciclo y el total de módulos.
-- Encuentra los alumnos que la ultima titulacion sea 'CFGM'.
-- Encuentra los alumnos que la ultima titulacion sea 'CFGM' o 'BACH'. Ordena por ultima titulacion
-- Cuenta el numero de alumnos existentes por cada ultima titulacion.
-- Lista los módulos que tienen una nota superior a 8.
-- Muestra el nombre y apellidos de los profesores que tienen un correo electrónico.
-- Lista los nombres de los profesores que imparten módulos en el ciclo DAM.
-- Muestra el nombre completo del profesor que tiene el contrato con el código 5.
-- Lista los módulos y las notas obtenidas por los alumnos en orden descendente de nota.
-- Calcula la media de todas las calificaciones existentes.
-- Calcula la media por módulo
-- Calcula la media por matricula.